In [ ]:
import torch
x=torch.arange(12).reshape(3,4)
print(x)
print(x.reshape(2,2,3))
y=x.reshape(2,2,3)
print(y.shape)
x1=torch.zeros(2,4)
print(x1)
print(torch.cat((x,x1),dim=0))
#import os
import os
#exist_ok=True表示如果路径已经存在，不会报错
os.makedirs(os.path.join('/home/pumengyu','limu'),exist_ok=True)
data_file=os.path.join('/home/pumengyu/','data','house_tiny.csv')
#with open这里的'w'如果data_file不存在，会创建，'w'会清空原有内容并且写入
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n')

    f.write('NA,Pave,127500\n')        # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')
import pandas as pd
data=pd.read_csv(data_file)
print("data=",data)
inputs=data.iloc[:,0:2]
output=data.iloc[:,2]

print("inputs",inputs)
inputs1=pd.get_dummies(inputs,dummy_na=True)
print("inputs1=",inputs1)

A=torch.arange(20).reshape(4,5)
print("A=",A)
# print("A.T=",A.T)
print(A.sum(axis=0).shape)
print(A.sum(axis=1).shape)
print(torch.mm(A,A.T))
#自动微分
x=torch.arange(4.0)
#等价于x=torch.arange(4.0,requires_grad=True)
x.requires_grad=True

x.grad#默认值是None
y=2*torch.dot(x,x)

y.backward()

x.grad
print("x",x)
print("x.grad=",x.grad)
print("y=",y)
y=x.sum()
x.grad.zero_()
y.backward()
print("x.grad1",x.grad)



tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([2, 2, 3])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]])
data=    NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000
inputs    NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0   NaN
3       NaN   NaN
inputs1=    NumRooms  Alley_Pave  Alley_nan
0       NaN        True      False
1       2.0       False       True
2       4.0       False       True
3       NaN       False       True
A= tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
torch.Size([5])
torch.Size([4])
tensor([[  30,   80,  130,

**概率论,**
```python
from torch.distribution import multinomial 

In [45]:
from torch.distributions import multinomial
fa=torch.ones(6)/6
print(fa)
fair=torch.ones([6])/6
print("fair=",fair)
a=multinomial.Multinomial(1000,fair).sample()
print("a",a/1000)
counts=multinomial.Multinomial(1000,fair).sample((500,))
print("counts.shape=",counts.shape)
print("counts.cumsum.shape=",counts.cumsum(dim=0).shape)
cum_counts=counts.cumsum(dim=0)

tensor([0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667])
fair= tensor([0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667])
a tensor([0.1720, 0.1660, 0.2020, 0.1510, 0.1570, 0.1520])
counts.shape= torch.Size([500, 6])
counts.cumsum.shape= torch.Size([500, 6])
